// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mockeryMocks

import (
	post "github.com/leoomi/GoTesting/pkg/post"
	mock "github.com/stretchr/testify/mock"
)

// PostService is an autogenerated mock type for the PostService type
type PostService struct {
	mock.Mock
}

// AddPost provides a mock function with given fields: _a0
func (_m *PostService) AddPost(_a0 post.Post) {
	_m.Called(_a0)
}

// GetPosts provides a mock function with given fields:
func (_m *PostService) GetPosts() []post.Post {
	ret := _m.Called()

	var r0 []post.Post
	if rf, ok := ret.Get(0).(func() []post.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]post.Post)
		}
	}

	return r0
}
